<?php
set_include_path('../php');

require_once 'enumeration.php';

enumeration::new_type('day', ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']);
$a = day::create('tue');
echo $a;
echo "\n";
echo $a->first;
echo "\n";
echo $a->last;
echo "\n";
print_r($a->range);
echo "\n";
echo $a->size;
echo "\n";
echo $a->pos_dynamic('sat');
echo "\n";
echo $a->pred_dynamic($a);
echo "\n";
echo $a->pred_dynamic('thu');
echo "\n";
echo $a->succ_dynamic('sat');
echo "\n";
echo $a->val_dynamic(4);
echo "\n";
echo "\n";

echo day::first();
echo "\n";
echo day::last();
echo "\n";
print_r(day::range());
echo "\n";
echo day::size();
echo "\n";
echo $a::pos('sat');
echo "\n";
echo day::pred($a);
echo "\n";
echo day::pred('thu');
echo "\n";
echo day::succ('sat');
echo "\n";
echo day::val(4);
echo "\n";
echo "\n";

day::new_type('mid_week', 'tue', 'fri');
$b = mid_week::create('tue');
echo $b;
echo "\n";
echo mid_week::first();
echo "\n";
echo mid_week::last();
echo "\n";
echo mid_week::pos($b);
echo "\n";
echo mid_week::pos('thu');
echo "\n";
echo mid_week::val(3);
echo "\n";
print_r(mid_week::range());
echo "\n";
echo "\n";
