package CONFIG is
//*
    OUTPUT_SCREEN_SIZE : INTEGER := 20;
    type CONFIGURATION_TYPE is (DEVELOPER_VERSION, USER_VERSION, ONLY_MEANINGS);
    CONFIGURATION : CONFIGURATION_TYPE := DEVELOPER_VERSION;
    type METHOD_TYPE is (INTERACTIVE, COMMAND_LINE_INPUT, COMMAND_LINE_FILES);
    METHOD : METHOD_TYPE := INTERACTIVE;
    type LANGUAGE_TYPE is (LATIN_TO_ENGLISH, ENGLISH_TO_LATIN);
    LANGUAGE : LANGUAGE_TYPE := LATIN_TO_ENGLISH;
    SUPPRESS_PREFACE : BOOLEAN := FALSE;
*//
    const OUTPUT_SCREEN_SIZE = 20;
    const CONFIGURATION_TYPE = ['DEVELOPER_VERSION', 'USER_VERSION', 'ONLY_MEANINGS'];
    const CONFIGURATION      = 'DEVELOPER_VERSION';
    const METHOD_TYPE        = ['INTERACTIVE', 'COMMAND_LINE_INPUT', 'COMMAND_LINE_FILES'];
    const METHOD             = 'INTERACTIVE';
    const LANGUAGE_TYPE      = ['LATIN_TO_ENGLISH', 'ENGLISH_TO_LATIN'];
    const LANGUAGE           = 'LATIN_TO_ENGLISH';
    const SUPPRESS_PREFACE   = false;
end CONFIG;
