<?php
class config
{
    const OUTPUT_SCREEN_SIZE = 20;
    const CONFIGURATION_TYPE = ['DEVELOPER_VERSION', 'USER_VERSION', 'ONLY_MEANINGS'];
    const CONFIGURATION      = 'DEVELOPER_VERSION';
    const METHOD_TYPE        = ['INTERACTIVE', 'COMMAND_LINE_INPUT', 'COMMAND_LINE_FILES'];
    const METHOD             = 'INTERACTIVE';
    const LANGUAGE_TYPE      = ['LATIN_TO_ENGLISH', 'ENGLISH_TO_LATIN'];
    const LANGUAGE           = 'LATIN_TO_ENGLISH';
    const SUPPRESS_PREFACE   = false;
}
